// *** WARNING: this file was generated by the Kulado Kubernetes codegen tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as kulado from "@kulado/kulado";
import * as inputApi from "../../types/input";
import * as outputApi from "../../types/output";
import { getVersion } from "../../version";

    /**
     * SelfSubjectAccessReview checks whether or the current user can perform an action.  Not
     * filling in a spec.namespace means "in all namespaces".  Self is a special case, because users
     * should always be able to check whether they can perform an action
     */
    export class SelfSubjectAccessReview extends kulado.CustomResource {
      /**
       * APIVersion defines the versioned schema of this representation of an object. Servers should
       * convert recognized schemas to the latest internal value, and may reject unrecognized
       * values. More info:
       * https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
       */
      public readonly apiVersion: kulado.Output<"authorization.k8s.io/v1">;

      /**
       * Kind is a string value representing the REST resource this object represents. Servers may
       * infer this from the endpoint the client submits requests to. Cannot be updated. In
       * CamelCase. More info:
       * https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
       */
      public readonly kind: kulado.Output<"SelfSubjectAccessReview">;

      
      public readonly metadata: kulado.Output<outputApi.meta.v1.ObjectMeta>;

      /**
       * Spec holds information about the request being evaluated.  user and groups must be empty
       */
      public readonly spec: kulado.Output<outputApi.authorization.v1.SelfSubjectAccessReviewSpec>;

      /**
       * Status is filled in by the server and indicates whether the request is allowed or not
       */
      public readonly status: kulado.Output<outputApi.authorization.v1.SubjectAccessReviewStatus>;

      /**
       * Get the state of an existing `SelfSubjectAccessReview` resource, as identified by `id`.
       * Typically this ID  is of the form <namespace>/<name>; if <namespace> is omitted, then (per
       * Kubernetes convention) the ID becomes default/<name>.
       *
       * Kulado will keep track of this resource using `name` as the Kulado ID.
       *
       * @param name _Unique_ name used to register this resource with Kulado.
       * @param id An ID for the Kubernetes resource to retrieve. Takes the form
       *  <namespace>/<name> or <name>.
       * @param opts Uniquely specifies a CustomResource to select.
       */
      public static get(name: string, id: kulado.Input<kulado.ID>, opts?: kulado.CustomResourceOptions): SelfSubjectAccessReview {
          return new SelfSubjectAccessReview(name, undefined, { ...opts, id: id });
      }

      /** @internal */
      private static readonly __kuladoType = "kubernetes:authorization.k8s.io/v1:SelfSubjectAccessReview";

      /**
       * Returns true if the given object is an instance of SelfSubjectAccessReview.  This is designed to work even
       * when multiple copies of the Kulado SDK have been loaded into the same process.
       */
      public static isInstance(obj: any): obj is SelfSubjectAccessReview {
          if (obj === undefined || obj === null) {
              return false;
          }

          return obj["__kuladoType"] === SelfSubjectAccessReview.__kuladoType;
      }

      /**
       * Create a authorization.v1.SelfSubjectAccessReview resource with the given unique name, arguments, and options.
       *
       * @param name The _unique_ name of the resource.
       * @param args The arguments to use to populate this resource's properties.
       * @param opts A bag of options that control this resource's behavior.
       */
      constructor(name: string, args?: inputApi.authorization.v1.SelfSubjectAccessReview, opts?: kulado.CustomResourceOptions) {
          let inputs: kulado.Inputs = {};
          inputs["apiVersion"] = "authorization.k8s.io/v1";
          inputs["kind"] = "SelfSubjectAccessReview";
          inputs["metadata"] = args && args.metadata || undefined;
          inputs["spec"] = args && args.spec || undefined;
          inputs["status"] = args && args.status || undefined;

          if (!opts) {
              opts = {};
          }

          if (!opts.version) {
              opts.version = getVersion();
          }
          super(SelfSubjectAccessReview.__kuladoType, name, inputs, opts);
      }
    }
